apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: registry-sso
  labels:
    app: sso
spec:
  additionalOptions:
    - name: proxy
      value: edge
  db:
    host: keycloak-db
    passwordSecret:
      key: password
      name: keycloak-db-secret
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
  hostname:
    hostname: registry-sso.apps.rkubis414.apicurio.integration-qe.com
  ingress:
    className: openshift-default
  http:
    httpEnabled: true
  instances: 1