config:
  configVersion: 5
application:
  shortName: "ApicurioRegistry"
  url: "http://<hostname>/apis/ccompat/v7"
scanners:
  zap:
    apiScan:
      apis:
        apiUrl: "http://<hostname>/api-specifications/ccompat/v7/openapi.json"

    spider:
      maxDuration: 0

    spiderAjax:
      maxDuration: 0
      browserId: firefox-headless

    activeScan:
      policy: "Kubernetes-API-scan"

    report:
      format: ["json","html"]