config:
  configVersion: 5
application:
  shortName: "ApicurioRegistry"
  url: "http://<hostname>/apis/cncf/v0"
scanners:
  zap:
    apiScan:
      apis:
        apiUrl: "http://<hostname>/api-specifications/cncf/v0/openapi.json"

    spider:
      maxDuration: 0

    spiderAjax:
      maxDuration: 0
      browserId: firefox-headless

    activeScan:
      policy: "Kubernetes-API-scan"